// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-AmKs7vkhe2MkH7nz8sG0g182Wk2zjB0',
    appId: '1:745869725996:web:ba580ba0c68823b8011c89',
    messagingSenderId: '745869725996',
    projectId: 'nihongo-first',
    authDomain: 'nihongo-first.firebaseapp.com',
    storageBucket: 'nihongo-first.firebasestorage.app',
    measurementId: 'G-FZ6PWBT1QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_suF6UoQ8tHUVWmmpqYrS0v8XK-KTKM',
    appId: '1:745869725996:android:158a8d291ff508f6011c89',
    messagingSenderId: '745869725996',
    projectId: 'nihongo-first',
    storageBucket: 'nihongo-first.firebasestorage.app',
  );
}
